version: "3.9"
services:
  web:
    build: .
    image: is-industria-site:latest
    container_name: is-industria-site
    ports:
      - "5173:5173"
      - "5174:5174"
    restart: unless-stopped

  backend:
    build: ./rh-backend/
    image: is-industria-site-backend:latest
    container_name: is-industria-site-backend
    ports:
      - "5001:5001"
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    ports: ["3307:3306"]